#!/bin/bash

# default values
devel_mode=0


usage()
{
  echo "Usage 1: install --devel-mode"
  echo "Usage 2: install"
  exit 2
}


PARSED_ARGUMENTS=$(getopt --name install -o d --long devel-mode -- "$@")

VALID_ARGUMENTS=$?
if [ "$VALID_ARGUMENTS" != "0" ]; then
  usage
fi


eval set -- "$PARSED_ARGUMENTS"
while :
do
  case "$1" in
    --devel-mode)   devel_mode=1      ; shift   ;;
    # -- means the end of the arguments; drop this, and break out of the while loop
    --) shift; break ;;
    # If invalid options were passed, then getopt should have reported an error,
    # which we checked as VALID_ARGUMENTS when getopt was called...
    *) echo "Unexpected option: $1 - this should not happen."
       usage ;;
  esac
done

if (( $devel_mode == 1 && $# != 0 || $devel_mode == 0 && $# != 0 )); then
    usage
fi

script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )"

echo script_dir is $script_dir

if [[ "$devel_mode" -eq 0 ]]; then
    cp "$script_dir"/base/bin/* /usr/local/bin
    cp "$script_dir"/base/libexec/* /usr/local/libexec
    shopt -s extglob # see https://unix.stackexchange.com/questions/41693/how-to-copy-some-but-not-all-files
    eval '
       # evaluation of this code is deferred otherwise shopt wont work for us
       cp "$script_dir"/base/systemd-unit-files/!(*.d) /etc/systemd/system
    '
    shopt -u extglob
    mkdir --parents /usr/local/share/ticketweb/authsystem
    cp "$script_dir"/authsystem/session_storage_schema.sql /usr/local/share/ticketweb/authsystem
else
    mkdir --parents "$HOME"/.local/bin
    mkdir --parents "$HOME"/.local/libexec
    ln --symbolic --force "$script_dir"/base/bin/* "$HOME"/.local/bin
    ln --symbolic --force "$script_dir"/base/libexec/* "$HOME"/.local/libexec
    mkdir --parents "$HOME"/.config/systemd/user
    ln --symbolic --force "$script_dir"/base/systemd-unit-files/ticketweb-authsystem-prunesessions@.* "$HOME"/.config/systemd/user
fi

