#!/bin/bash


#default values
devel_mode=0
venv_id=unset
ticketweb_venv_root=unset


usage()
{
  echo "Usage: ticketweb-authsystem-prunesessions <ticketweb_venv_root>"
  exit 2
}



if [[ -z $1 ]]; then
    usage
fi


ticketweb_venv_root=$1



source $ticketweb_venv_root/bin/activate


python -c "from ticketweb_authsystem_server import sessions; sessions.prune_old_sessions()"



