#!/bin/bash


#default values
devel_mode=0
venv_id=unset
ticketweb_venv_root=unset


usage()
{
  echo "Usage 1: ticketweb-authsystem-prunesessions --devel-mode <ticketweb_venv_root>"
  echo "Usage 2: ticketweb-authsystem-prunesessions <ticketweb_venv_id>"
  exit 2
}


PARSED_ARGUMENTS=$(getopt --name ticketweb-authsystem-prunesessions -o d --long devel-mode -- "$@")

VALID_ARGUMENTS=$?
if [ "$VALID_ARGUMENTS" != "0" ]; then
  usage
fi


eval set -- "$PARSED_ARGUMENTS"
while :
do
  case "$1" in
    --devel-mode)   devel_mode=1      ; shift   ;;
    # -- means the end of the arguments; drop this, and break out of the while loop
    --) shift; break ;;
    # If invalid options were passed, then getopt should have reported an error,
    # which we checked as VALID_ARGUMENTS when getopt was called...
    *) echo "Unexpected option: $1 - this should not happen."
       usage ;;
  esac
done


if [[ -z $1 ]]; then
    usage
fi



if [[ "$devel_mode" -eq 0 ]]; then
    venv_id=$1
    venv_roots_file=/etc/ticketweb_venv_roots.json
    ticketweb_venv_root=$(cat "$venv_roots_file" | jq ."$venv_id" | tr -d '"')
else
    ticketweb_venv_root=$1
fi



source $ticketweb_venv_root/bin/activate
python -c "from ticketweb_authsystem_server import sessions; sessions.prune_old_sessions()"

